version: '3.8'
services:
  sender:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - FIFO_PATH=/fifo/bitfifo
      - MACADDRESS=aabbccddee01
    volumes:
      - ./tmp:/fifo
    command: sh -c "php src/sender.php"
    tty: true  # 標準入力を有効にする場合

  receiver:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - FIFO_PATH=/fifo/bitfifo
      - MACADDRESS=aabbccddee02
    volumes:
      - ./tmp:/fifo
    depends_on:
      - sender
    command: sh -c "php src/receiver.php"

